/**
 * Polymerch Product Catalog — PM Store 2026
 * Images live at: assets/images/ (relative to site root)
 * images[0] is used as the shop grid thumbnail.
 * Add Shopify variant IDs per size once the store is connected.
 */
const PRODUCTS = [
  {
    id: 'black-quarter-zip',
    name: 'BLACK QUARTER-ZIP',
    material: '100% COTTON FLEECE',
    sizing: 'UNISEX',
    price: 129,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40923.jpg',
      'assets/images/Group 40922.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'gray-quarter-zip',
    name: 'GRAY QUARTER-ZIP',
    material: '100% COTTON FLEECE',
    sizing: 'UNISEX',
    price: 129,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40924.jpg',
      'assets/images/Group 40925.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'polymarket-hoodie',
    name: 'POLYMARKET HOODIE',
    material: '100% COTTON FLEECE',
    sizing: 'UNISEX',
    price: 149,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    // colorVariants: each entry has name + the image for that colorway
    colorVariants: [
      { name: 'GRAY',     image: 'assets/images/Group 40921.jpg' },
      { name: 'NAVY',     image: 'assets/images/Group 40949.jpg' },
      { name: 'CHARCOAL', image: 'assets/images/Group 40951.jpg' },
    ],
    images: [
      'assets/images/Group 40921.jpg', // default shown before color selected
    ],
    shopifyVariants: {},
  },
  {
    id: 'white-track-set',
    name: 'WHITE TRACK SET',
    material: 'POLY BLEND',
    sizing: 'UNISEX',
    price: 298,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40926.jpg',
      'assets/images/Group 40927.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'navy-track-set',
    name: 'NAVY TRACK SET',
    material: 'POLY BLEND',
    sizing: 'UNISEX',
    price: 298,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40928.jpg',
      'assets/images/Group 40929.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'royal-slides',
    name: 'ROYAL SLIDES',
    material: 'WOAD-DYED COTTON',
    sizing: 'UNISEX',
    price: 129,
    sizes: ['6', '7', '8', '9', '10', '11', '12', '13'],
    sizeType: 'shoe',
    images: [
      'assets/images/Group 40930.jpg',
    ],
    shopifyVariants: {},
    sizeGuide: [
      { us: '6',  eu: '38',    uk: '5.5',  cm: '24' },
      { us: '7',  eu: '39',    uk: '6.5',  cm: '25' },
      { us: '8',  eu: '40–41', uk: '7.5',  cm: '26' },
      { us: '9',  eu: '42',    uk: '8.5',  cm: '27' },
      { us: '10', eu: '43',    uk: '9.5',  cm: '28' },
      { us: '11', eu: '44–45', uk: '10.5', cm: '29' },
      { us: '12', eu: '46',    uk: '11.5', cm: '30' },
      { us: '13', eu: '47',    uk: '12.5', cm: '31' },
    ],
  },
  {
    id: 'human-intelligence-tee',
    name: 'HUMAN INTELLIGENCE TEE',
    material: '100% COTTON',
    sizing: 'UNISEX',
    price: 69,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40932.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'corduroy-cap',
    name: 'CORDUROY CAP',
    material: 'CORDUROY',
    sizing: 'ONE SIZE',
    price: 49,
    sizes: ['ONE SIZE'],
    sizeType: 'one-size',
    colorVariants: [
      { name: 'NAVY / GOLD' },
      { name: 'BLACK / GOLD' },
      { name: 'NAVY / WHITE' },
      { name: 'BLACK / WHITE' },
    ],
    images: [
      'assets/images/Group 40933.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'tarot-hoodie',
    name: 'TAROT HOODIE',
    material: '100% COTTON FLEECE',
    sizing: 'UNISEX',
    price: 159,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40934.jpg',
      'assets/images/Group 40935.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'blue-sweat-set',
    name: 'BLUE SWEAT SET',
    material: '100% COTTON FLEECE',
    sizing: 'UNISEX',
    price: 258,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40937.jpg',
      'assets/images/Group 40936.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'white-long-sleeve',
    name: 'WHITE LONG SLEEVE',
    material: '100% COTTON',
    sizing: 'UNISEX',
    price: 89,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40938.jpg',
      'assets/images/Group 40939.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'black-long-sleeve',
    name: 'BLACK LONG SLEEVE',
    material: '100% COTTON',
    sizing: 'UNISEX',
    price: 89,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40940.jpg',
      'assets/images/Group 40941.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'navy-zip-jacket',
    name: 'NAVY ZIP JACKET',
    material: '100% COTTON TWILL',
    sizing: 'UNISEX',
    price: 249,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    sizeType: 'apparel',
    images: [
      'assets/images/Group 40942.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'black-tote',
    name: 'BLACK TOTE',
    material: 'HEAVYWEIGHT CANVAS',
    sizing: 'ONE SIZE',
    price: 69,
    sizes: ['ONE SIZE'],
    sizeType: 'one-size',
    images: [
      'assets/images/Group 40950.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'newspaper-tote',
    name: 'NEWSPAPER TOTE',
    material: 'HEAVYWEIGHT CANVAS',
    sizing: 'ONE SIZE',
    price: 79,
    sizes: ['ONE SIZE'],
    sizeType: 'one-size',
    images: [
      'assets/images/Group 40943.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'tarot-tote',
    name: 'TAROT TOTE',
    material: 'CANVAS',
    sizing: 'ONE SIZE',
    price: 89,
    sizes: ['ONE SIZE'],
    sizeType: 'one-size',
    images: [
      'assets/images/Group 40945.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'magic-8-ball',
    name: 'MAGIC 8-BALL',
    material: 'ABS PLASTIC',
    sizing: 'ONE SIZE',
    price: 39,
    sizes: ['ONE SIZE'],
    sizeType: 'one-size',
    images: [
      'assets/images/Group 40946.jpg',
    ],
    shopifyVariants: {},
  },
  {
    id: 'cable-knit-socks',
    name: 'CABLE KNIT SOCKS',
    material: 'COTTON BLEND',
    sizing: 'ONE SIZE',
    price: 29,
    sizes: ['ONE SIZE'],
    sizeType: 'one-size',
    colorVariants: [
      { name: 'CREAM' },
      { name: 'NAVY' },
    ],
    images: [
      'assets/images/Group 40948.jpg',
    ],
    shopifyVariants: {},
  },
];

function getProductById(id) {
  return PRODUCTS.find(p => p.id === id) || null;
}
